#!/bin/bash

rm calculator/calculator_1.0.orig.tar.xz
rm calculator/calculator_1.0-1.dsc
rm calculator/calculator_1.0-1.debian.tar.gz
rm calculator/calculator_1.0-1_all.deb
rm calculator/calculator_1.0-1_amd64.changes
